jellyfin/jellyfin-mpv-shim

README.md, jellyfin_mpv_shim/jellyfin/http.py, setup.py
Removes six. There's no reason to use it when jellyfin-mpv-shim is a Python 3-only app.
=> Remove six

jellyfin_mpv_shim/conf.py, jellyfin_mpv_shim/media.py
Since jellyfin/jellyfin#2295 is accepted, direct play over SMB/NFS can be used which is more reliable, consumes less memory and better experience overall (for me at least).
=> Add direct paths support

jellyfin_mpv_shim/media.py
This simply checks if the direct path is an existing local file before using it, and only does so if it has no uri scheme.
=> If using direct local paths, check if the file exists

jellyfin_mpv_shim/utils.py
As socket.gethostbyname is not support ipv6, use socket.getaddrinfo instead.   
Also skip local check for ipv6 and return false for few people use private ipv6.May be a prefix compare is better.  
The port param in socket.getaddrinfo is not matter.
=> Fix ipv6 in is_local_domain

jellyfin_mpv_shim/media.py
I had to write my guest credentials into my native path for Kodi, but then it didn't work for mpv shim. So I wrote a few lines that rewrote the path if it matched an regex.
=> rewrite smb url with credentials to url without credentials in windows

jellyfin_mpv_shim/media.py
Hi, I tested if #84 was merged correctly in the build and it seems that I wrote a bug. The regex parsing happens only in the remote direct path section of media.py. I put it in front of both local and remote direct path sections and it works now.
=> fixed URL rewrite only happening in remote_direct_paths 

CONTRIBUTING.md, README.md
Mac OS X was renamed to macOS, and readme should reflect that.
Also, searching was a bit confusing, since it was sometimes references as `OSX`, and other times as `Mac OSX`.
=> Rename OSX -> macOS

README.md
more explicit that the config is in the user's `Library` folder, not the system's.
this gave me a moment of confusion while looking for the config json.
=> update config to point to user's Library folder

jellyfin_mpv_shim/menu.py, jellyfin_mpv_shim/player.py
Changed `capture_mouse` to `triggered_menu`
The current capture_mouse event is triggered when the menu shows. This is more generic as the event can be used for various lua scripts other than mouse capture.
=> Changed capture_mouse to be more generic

Jellyfin MPV Desktop.iss, jellyfin_mpv_shim/clients.py, jellyfin_mpv_shim/constants.py, jellyfin_mpv_shim/event_handler.py, jellyfin_mpv_shim/integration/com.github.iwalton3.jellyfin-mpv-shim.appdata.xml, jellyfin_mpv_shim/webclient_view/__init__.py, setup.py
#191 Playing media from episode page crashes player logic and doesn't set subtitle/audio streams.
#194 Fix erratic navigation in webclient caused by sending back bad display mirror events.
#193 Handle trailing slashes in server URLs.
=> Fix bugs #191, #194, #193

jellyfin_mpv_shim/player.py, jellyfin_mpv_shim/rich_presence.py, jellyfin_mpv_shim/syncplay.py
With this, you can send Discord invites, while being in a SyncPlay group. Others can then join the group in Discord.
This idea was suggested in #148
Unfortunately, joining only works if there's already a video playing, as the rich-presence needs to be updated for pypresence to process the join event.
=> Allow joining SyncPlay groups via Discord invites

jellyfin_mpv_shim/gui_mgr.py
`title` is the real display name, not `name`.  
If `title` not provided, tray entry will be named as executable.
With this change, it will be consistently "Jellyfin MPV Shim".
=> set title to USER_APP_NAME

jellyfin_mpv_shim/gui_mgr.py, jellyfin_mpv_shim/log_utils.py, jellyfin_mpv_shim/mpv_shim.py
Use mpv_log_level to set shim logger level too.
That should remove excessive chatter from pings to the server.
Set level to INFO by default. During normal operations people don't need to have debug enabled.
Fixes #372
=> make shim logger configurable

jellyfin_mpv_shim/trickplay-osc.lua
mpv-player/mpv@86b498e removed deprecated utils.shared_script_property_set. Since deprecation was ignored for years, it eventually broke jellyfin-mpv-shim.
Fixes #376
=> switch to "user-data" property for storing values

jellyfin_mpv_shim/clients.py
Fixes #390 
Several users reporting that a 1 second sleep is enough, but 3 seconds won't hurt anything and gives more time for those rare users running their servers on literal potatoes.
=> Add processing delay during startup

jellyfin_mpv_shim/media.py
Hi, this PR adds the missing `LiveStreamId` query param (see [jellyfin-web](https://github.com/jellyfin/jellyfin-web/blob/eaee9a975afa33ebdf6833c6b203e876abb548f9/src/components/playback/playbackmanager.js#L2741)) when requesting a video stream.
This should allow jellyfin-mpv-shim to play Live TV streams.
=> Support live tv streams

jellyfin_mpv_shim/conffile.py, jellyfin_mpv_shim/gui_mgr.py
This PR:
- Modifies `conffile.py` to allow OpenBSD to use the `posix` configuration file locations
- Modifies `gui_mgr.py` to allow OpenBSD to use the `xdg-open` command for opening files
- Renames `_show_file_linux` to `_show_file_xdg` given it is now shared between Linux and OpenBSD
- Updates `show_file` in `gui_mgr.py` to be set based on a matching platform prefix, instead of just an explicit match, as OpenBSD values for `sys.platform` are values like `openbsd7` rather than `openbsd`. Other platforms likely behave the same way.
=> Two small OpenBSD support improvements

jellyfin_mpv_shim/mpv_shim.py
On non-glibc systems, event.wait() is not guaranteed to return on keyboard interrupt.
There is some further context in this [SO question](https://stackoverflow.com/questions/51083939/why-can-pythons-event-wait-be-interrupted-by-signals-on-some-systems-but-not), the short version is the syscall used by Python internally during event.wait() only optionally returns on interrupt per POSIX. On glibc systems, the syscall will be interrupted by Control+C, so event.wait() works as expected by this program. The effect on other operating systems (such as OpenBSD, and likely others) is that event.wait() will continue to wait even if Control+C is pressed.
This small change sets a timeout on the wait, and loops indefinitely until the program is interrupted. This allows the progrram an opportunity to …
=> Make main halt event work on non-glibc systems

jellyfin_mpv_shim/gui_mgr.py
Currently if pystray throws any exceptions, the exception is passed through but not caught.
Without catching systray exceptions, the systray icon can be removed (i.e. by selecting Quit from the menu) without signalling to the rest of the program that it should shut down.
This happens for example if you run jellyfin-mpv-shim on a system which does not have a notifications daemon registered with dbus, pystray emits an exception when it tries to remove any lingering notifications. This fails, and jellyfin-mpv-shim is left without a systray icon, but still running in the background.
With this patch, a systray exception will gracefully terminate jellyfin-mpv-shim. It would be possible to selectively target individual exceptions which would trigger this behaviour, however looking at the other …
=> Catch exceptions from pystray

jellyfin_mpv_shim/player.py
This avoids crashing when using unofficial discord clients like vesktop that use arrpc for their rpc support.
=> Catch exceptions when registering Discord join callback

jellyfin_mpv_shim/clients.py
This pull request fixes a bug where MPV Shim disconnects itself immediately after starting, even though the WebSocket connection is successfully established.
The problem occurs in validate_client(), which fetches the session list using the ControllableByUserId filter. Right after a restart, Jellyfin has not yet fully registered the new session or attached the UserId. As a result, the filtered /Sessions query returns an empty list, causing the client to falsely assume it is not connected and to close the WebSocket.
This change removes the ControllableByUserId filter from the initial session query. Instead, the code checks for the presence of the correct DeviceId in the full session list. This avoids premature disconnects while still preserving the integrity of the session verification. …
=> Bug Fix: Prevent false “not connected” state after MPV Shim restart
